# Generated by Django 2.1.4 on 2019-01-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20190113_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='artical',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='demo.Artical'),
        ),
    ]
