# Generated by Django 2.1.4 on 2019-01-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20190113_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='likenum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
