# Generated by Django 2.1.4 on 2019-01-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_artical_likenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
